config/routes.rb
Rails.application.routes.draw do

 root "catalogs#index"

   get "/hi" => "catalogs#index"
   get "/gu" => "catalogs#index"
   get "/mr" => "catalogs#index"
   get "/te" => "catalogs#index"
   get "/ta" => "catalogs#index"
   get "/kn" => "catalogs#index"
  
  catgrs = ['bollywood-plus', 'bollywood-classic','gujarati','marathi','kids','comedy','bhakti','punjabi','ibaadat','video','movie','show','livetv','hot-movie']
  catgrs.each do |c|
    get "/:lang/#{c}" => "catalogs#indiv_category_landing"
  end

  get "/channels" => "catalogs#channel_catalog_item"
  get "/:lang/channels" => "catalogs#channel_catalog_item"
  get "/all_channels_playlist/:cat_name" => "catalogs#all_channels_playlist"
  get "/:lang/all_channels_playlist/:cat_name" => "catalogs#all_channels_playlist"
  get "/catalogs/more_channels_list" => "catalogs#more_channels_list"

  get "/live-tv-1/all" => "catalogs#show_catalog_item"


  get '/plans' => 'plans#all_plans'
  get '/:lang/plans' => 'plans#all_plans'

 
 require 'sidekiq/web'
 mount Sidekiq::Web => '/sidekiq_shemaroo'

 ##STATIC PAGES ROUTES STARTS HERE####
 get "/terms-and-conditions" => "statics#terms_conditions"

 
 #Main referal route for showing FAQ and TAQ based on Region
 get "/referal_terms_conditions" => "statics#referal_terms_conditions"


 get "/.well-known/apple-app-site-association" => "statics#apple_site_notification"

 get "/.well-known/pki-validation/BA4DB7294E74E2DFF9157CDBE07F934F.txt" => "statics#pki_txt"

 get "/offers" => "statics#offers"

 get "/worldmeday" => "statics#worldmeday"

 get "/rehlatoffer" => "statics#rehlatoffer"

 get "/8koffers" => "statics#offers"

 get "/hotstar" => "statics#hotstar"

 get "/hotstar1" => "statics#hotstar1"

 get "/gifts" => "statics#gifts"

 get "/shemaroo_docs_offer" => "statics#shemaroo_doc_app"

 get "/digital_marketing" => "statics#digital_marketing"

 get "/terms_and_conditions" => "statics#terms_conditions"

 get "/:lang/terms_and_conditions" => "statics#terms_conditions"


 get "/etisalat_termsconditions" => "statics#etisalat_terms"

 get "/etisalat_privacy_policy" => "statics#etisalat_privacy_policy"

 get "/etisalat_faq" => "statics#etisalat_faq"

 get "/gujarati-landing" => "statics#gujarathi_landing"

 get "/bollywood-landing" => "statics#bollywood_landing"

 get "/best-of-bollywood-entertainment" => "statics#bollywood_landing"

 get "/best-of-gujarati-entertainment" => "statics#gujarathi_landing"

 get "/gujarati-landing_page" => "statics#gujarathi_landing_page"

 get "/accentiv"  => "statics#accentiv"

 get "/:lang/contest_gamification" => "statics#contest_gamification"

 get "/contest_gamification" => "statics#contest_gamification"

 get "/partners" => "catalogs#partner"

 get "/partners-db" => "catalogs#partner"

 get "/comingsoon" => "statics#coming_soon"

 get "/consulategeneraln" => "statics#consulate_general"

 get "/CGNY" => "statics#consulate_general"

 get "/cgny" => "statics#consulate_general"

 get "/rajchandraji" => "statics#rajchandraji"

 get "/EOIP" => "statics#eoip"

 get "/eoip" => "statics#eoip"

 get "/allaccessoffer" => "statics#all_access_offer"
 get "/blackfriday" =>"statics#blackfriday"
 get "/ALLACCESSOFFER" => "statics#all_access_offer"

 get "/GujaratiOffer" => "statics#gujaratioffer"
 get "/BollyPremiereOffer" => "statics#bollypremiereoffer"
 get "/BollyClassicOffer" => "statics#bollyclassicoffer"

 get "/gujaratioffer" => "statics#gujaratioffer"
 get "/bollypremiereoffer" => "statics#bollypremiereoffer"
 get "/bollyclassicoffer" => "statics#bollyclassicoffer"
 get "/lohana-samaj" => "statics#lohana_samaj"
 get "/Lohana-Samaj" => "statics#lohana_samaj"
 get "/navratri"  => "statics#navratri"
 get "/NAVRATRI"  => "statics#navratri"
 get "/guj" => "statics#guj_landing"
 get "/bhavans" => "statics#bhavans"
 get "/gujm" => "statics#gujm"
 get "/usswagatam" => "statics#us_swagatam"
 get "/usvat-vat-ma" => "statics#hungamacity"
 get "/gcs-alabama" => "statics#gcs_alabama"
 get "/montgomery" => "statics#montgomery"
 get "/vyo" => "statics#vyo_landing"
 get "/gs-alabama" => "statics#gs_alabama"
 get "/gona" => "statics#gona"
 get "/gsdetroit" => "statics#gsdetroit"
 get "/gcs-florida" => "statics#gcs_florida"
 get "/vtofny"  => "statics#vtofny"
 get "/phillymm" => "statics#phillymm"
 get "/fog-canada"=> "statics#fog_canada"
 get "/mobikwik_terms" => "statics#mobikwik_terms"
 get "/grievance" => "statics#grievance"
 get "/bolly" => "statics#bollywood_category"

 get "/GSHOUSTON" => "statics#gshouston"
 get "/gshouston" => "statics#gshouston"
 get "/gmoco" => "statics#gmoco"
 get "/GMOCO" => "statics#gmoco"

 get "/gujaratisamaj" => "statics#gujaratisamaj"

 post "/payment/payu_payment_response" => "plans#payu_payment_response"
 

 get "/homeis" => "statics#homeis"

 get "/HOMEIS" => "statics#homeis"

  get "/CGIC" => "statics#cgic"

  get "/cgic" => "statics#cgic"

  get "/HCIC" => "statics#hcic"

  get "/hcic" => "statics#hcic"

  get "/cgny2" => "statics#cgny2"

  get "/eois" => "statics#eois"

  get "/EOIS" => "statics#eois"

 get "/privacy-policy" => "statics#privacy_policy"

 get "/:lang/privacy-policy" => "statics#privacy_policy"
 get "/privacy_policy" => "statics#privacy_policy"

  get "/cookie-policy" => "statics#cookie_policy"

  get "/offer_terms_conditions" =>  "statics#offer_terms_conditions"

  get "/offer_rules_regulations" =>  "statics#offer_rules_regulations"

 get "/content_not_available" => "statics#content_not_available"

 get "/faq" => "statics#faq"


 get "/about-us" => "statics#about_us"
 
 get "/:lang/faq" => "statics#faq"

 get "/thanks" => "statics#thanks"

 get "/health_check" => "statics#health_check"

 get "/landing_page" => "statics#landing_page"

 get "/engage_page" => "statics#engage_page"

 get "/:lang/contact-us" => "statics#contact_us"

 match "/contact-us" => "statics#contact_us",via: [:get,:post]

 get "/referral_earn_money" => "statics#ref_earn_money"

 get "/icicim2i" => "statics#icic"
 
 get "/:lang/tv" => "users#activate_code"

 get "/tv" => "users#activate_code"

 post "/users/coupon_register"  => "users#coupon_register"

 get "/sulekha" =>  "statics#sulekha"
 get "/hungamacity" =>  "statics#hungamacity"
 get "/HUNGAMACITY" =>  "statics#hungamacity"
 get "/store" => "statics#us_swagatam"
 get "/store1" => "statics#store1"
 # get "/bollywoodclassic" => "statics#shemaroo_classic"
 get "/bollywoodclassic" => "statics#microsite_classic"
 get "/evergreen" => "statics#evergreen_classic"
 get "/nyl" => "statics#nyl"

 ##STATIC PAGES ROUTES ENDS HERE####

 ##USERS PAGES ROUTES STARTS HERE####
  post "/participate" => "users#participate"
  get "/contest" => "users#contest"
  get "/subscribe-and-win-contest" => "users#contest"
  get "/subscribe-win-contest" => "users#subs_contest"
  match "/contest_questions" => "users#contest_questions",via: [:get,:post]

  get  "/:lang/users/sign_in" => "users#sign_in"
  get  "/:lang/users/profile" => "users#profile"
  get  "/:lang/users/watch_list"=> "users#watch_list" 
  get  "/:lang/users/settings" => "users#settings" 
  get  "/:lang/users/create_pin" => "users#create_pin" 
  get  "/:lang/users/referral" => "users#referral" 
  get  "/:lang/users/referral_earn_money" => "users#referral_earn_money"
  get  "/:lang/users/reset_pin"  => "users#reset_pin" 
  get  "/:lang/users/account_details" => "users#account_details"
  get  "/:lang/users/change_password" => "users#change_password" 
  get  "/:lang/users/redeem_ticket" => "users#redeem_ticket" 
  get  "/:lang/users/manage_profiles" => "users#manage_profiles" 
  get  "/:lang/users/referral_code" => "users#referral_code"
  get  "/:lang/users/registered_devices" => "users#registered_devices"
  get  "/:lang/users/who_is_watching" => "users#who_is_watching"
  get  "/:lang/users/verify_pin" => "users#verify_pin"
  get  "/:lang/users/my_earnings" => "users#my_earnings"
  get "/:lang/users/add_bank_account" => "users#add_bank_account"
  get "/:lang/users/continue_watching" => "users#continue_watching"
  post "/:lang/users/continue_watching" => "users#continue_watching"
  get "/:lang/users/user_recommendation" => "users#user_recommendation"
  post "/:lang/users/user_recommendation" => "users#user_recommendation"
  get "/:lang/users/gamification" => "users#gamification"
  get "/:lang/users/forgot_password" => "users#forgot_password"
  get "/:lang/users/forgot_pin" => "users#forgot_pin"
  get "/:lang/users/gmfc_contest" => "users#gmfc_contest"
  get "/:lang/users/gmfc_contest_questions" => "users#gmfc_contest_questions"
  get "/:lang/users/gmfc_winners" => "users#gmfc_winners"
  get "/:lang/users/gmfc_thanks" => "users#gmfc_thanks"
  get "/:lang/users/login" => "users#login"
  get "/search/all" => "search#all_items"
  get "/shu-thayu/tnc" => "users#shuthayu_tnc"
	namespace :users do
    match 'account_details', via: [:get,:post]
    match 'change_password',via: [:get,:post]
    match 'redeem_ticket',via: [:get,:post]
    match 'reset_pin',via: [:get,:post]
    get 'settings'
    match 'referral',via: [:get,:post]
    match  'watch_list',via: [:get,:post]
    match 'create_pin',via: [:get,:post]
    match 'sign_in', via: [:get,:post]
    post 'check_coupon_validity'
    post 'sub_events'
    get 'manage_profiles'
	  get 'register'
    get 'get_location_details'
    post 'pre_register'
	  get 'login'
    get 'sign_in'
    get 'profile'
	  post 'sign_up'
	  get 'welcome'
    get 'welcome_offer'
    match 'forgot_password_otp_verify', via: [:get,:post]
    match 'reset_password', via: [:get,:post]
    match 'reset_password_email', via: [:get,:post]
    match 'forgot_password',via: [:get,:post]
    match 'telco_external_users',via: [:get,:post]
    get 'change_profile'
	  post 'sign_out'
	  get  'verify_otp'
    get  'otp_verify'
    post 'update_profile'
    post 'delete_profile'
    match 'registered_devices',via: [:get,:post]
    get 'streaming'
    get 'parent_control'
    match 'activate_code',via: [:get,:post]
    match  'update_personal_details',via: [:get,:post]

app/helpers/catalogs_helper.rb
module CatalogsHelper

 

end

app/views/catalogs/_branch_banner_events.html.erb
<script type="text/javascript">
$(document).ready(function(){
  function decrypt_string(val){
    if(val.length == 0){
      val = "false"
    }
    var token = "92a7d1a410d84495fcf4c29e2a674a3c"
    var data  = CryptoJS.AES.decrypt(val.toString(),token).toString(CryptoJS.enc.Utf8);
    return data;
  }

  $(".banner_tag").click(function(){
    var det = $(this).attr("id").split("|");
    var category_name = det[1]
    var title = det[0]
    var content_id =  det[2]
    var content_type = det[3]
    var user_state = ""
    var region = $(".user_region").val();
    var user_city = $(".user_city").val();
    var branch_name = ""
    var user_type = ""
    //var sub_status = decrypt_string(getShemarooCookies().user_sub_status) 
    var sub_status = getShemarooCookies().user_state
    var session_id = ""
    var today = new Date();
    var date = today.getDate()+'-'+(today.getMonth()+1)+"-"+today.getFullYear();
    var h =  today.getHours(), m = today.getMinutes();
    var time = (h > 12) ? (h-12 + ':' + m +' PM') : (h + ':' + m +' AM');
    var free_trial_status = getShemarooCookies().user_period
    if($.cookie('user_id') != undefined){
      session_id = $.cookie('user_id')
    }
    if(getShemarooCookies().user_id == undefined){
      user_state = "anonymous"
      branch_name = "Banner_Clicks_Anonymous_user"
    }
    else{
      user_state = "loggedin"
      branch_name = "Banner_Clicks_Logged_In_User"
      if(sub_status == "Subscribed"){
        branch_name = "Banner_Clicks_Subscribed_User"
        user_type = (free_trial_status == "free_trial") ? "free" : "subscribed"
      }
    }
    
    smartech('dispatch', branch_name, {
      'title': title,
      'content_id': content_id,
      'category': category_name, 
      'content_type': content_type, 
      'user_state': user_state,
      'user_period': user_type,
      'region': region,
      'city': user_city,
      'date_event': date,
      'time_event': time,
      'session_id': session_id,
      'banner_type': "carousel"
      });

    _paq.push(['trackEvent', 'Media', 'Activity', branch_name, 1, { dimension3: category_name, dimension4: content_type, dimension10: user_state, dimension11: user_type,  dimension15: content_id, dimension16: title, dimension29: date, dimension30: time, dimension31: region, dimension32: user_city, dimension33: session_id }]);


      branch.logEvent(
       branch_name,
        {"title": title,
        "content_id": content_id,
        "category": category_name, 
        "content_type": content_type, 
        "user_state": user_state,
        "user_period": user_type,
        "region": region,
        "city": user_city,
        "date_event": date,
        "time_event": time,
        "session_id": session_id,
        "banner_type": "carousel"
        },
       function(err) { console.log(err); }
      );  
  })
})
</script>

app/views/catalogs/all_channels.html.erb
<%
meta title: "All tv channels",
     description: "All tv channels",
     keywords: "All tv channels"
%>

<div class="padding-top-80 padding-top-100 padding-top-70">
  <div class="min-height-div">
    <section class="full-width-content inside-container light padding-bottom-20">
      <%if @all_channels.count > 0%>
      <div class="row h-100">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- desktop-margin-top-10 listing-page">
          <div class="row">
           <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
          <h2 class="section-title big-desktop-app-font3 app-color1">All Channels</h2>
        </div>
        </div>
        <div class="row row-show-list all_show_horizontal_title">
         <%@all_channels.each do |i|%>
            <div class="item rounded <%=i["catalog_object"]["plan_category_type"] == "kids" ? "kids_channels" : "non_kids_channels"%>">                                             
              <a href="<%=get_item_url(i)%>" class="channel_item" data-channel-name = "<%=i['title']%>">
              <%if i['access_control']['is_free'] == false && i['access_control']['premium_tag'] == true && $region == "IN" %>
              <div class="h-center">
                <span class="text-uppercase premium-txt">Premium</span>
              </div>
              <%end%>
              <%if i["theme"] == "live"%>
              <!-- <span class="live-txt text-uppercase all_channels_live_txt">live</span> -->
              <%end%>
              <img src="<%=i["thumbnails"]["small_16_9"]["url"]%>" class="rounded" alt="<%=i['title']%>" title="<%=i['title']%>">
                <span class="list-tile-title"><%=i['title']%></span>
              </a>
            </div>
          <%end%>
        </div>  
        </div>  
      </div>
      <%else%>
      <div class="light no-items-found">
          <img src="/assets/no_content.svg" class="margin-bottom-10 welcome_page_image"  alt="" title="">
          <p class="font-mbold margin-top-25 margin-bottom-0"><strong>Sorry!</strong></p>
          <p class="font-mregular margin-top-0 margin-bottom-5">There is no channels to show</p>
          <p class="pull-left w-100 margin-top-20 margin-bottom-15 text-center">
            <a href="/" class="text-uppercase btn btn-outline-primary gradient1 radius-button">go back</a>
          </p>
        </div>
      <%end%>

    </section>
    <%=render "layouts/page_height_setting"%>
  </div>
</div>


<script type="text/javascript">
$(document).ready(function(){
  $(".scrollmenuwrap").hide();
  $("#header_tv_icon").addClass("tv_highlighted");
  //$("#tv_icon").attr("src","/assets/tv_w_highlight.svg");
  $("#tv_icon").attr("src","/assets/tv_active.svg");
  
  if(getShemarooCookies().user_id){
     if(getShemarooCookies().user_profile_type == "kids"){
       $(".non_kids_channels").hide();
     }
  }

  $(".channel_item").click(function(){
  var channel_name = $(this).data("channel-name")
  Netcore_Browse_Tv(channel_name)
})
function Netcore_Browse_Tv(channel_name){
console.log("netcore Netcore_Browse_Tv----------------------------",channel_name)
var user_region = $(".user_region").val()
smartech('dispatch', 'Browse_Tv', {
"user_id": getShemarooCookies().user_analytical_id,
"channel_name": channel_name,
"COUNTRY": user_region
 });
/*
Apxor.logEvent('Browse_Tv', {
"channel_name": channel_name,
"COUNTRY": user_region
 },"BROWSE");*/

} 
});
</script>

app/views/catalogs/all_items_list.html.erb
<%
meta title: "#{@title}",
     description: "",
     keywords: ""
%>
<div class="float-left w-100 wrapper listing-page">
  <div class="container">    
    <div class="float-left w-100 ">
      <div class="float-left w-100">
        <section class="main-content">
          <div class="float-left w-100 min-height-div">
            <ul class="ml-3 float-left w-100 list-none p-0 ml-4 breadcrumbs d-none d-xl-block">
              <li class="float-left font-regular home">
                <a href="/<%=params[:lang]%>"><%= get_lang_string("home")%></a>
              </li>
              <li class="float-left font-regular">
                <%= raw(get_brd_name(@theme))%>
              </li>
              <li class="float-left font-regular">
                <%=@title%>
              </li>        
            </ul>
            <ul class="ml-3 mt-2 float-left w-100 list-none p-0 breadcrumbs d-block d-xl-none">
              <li class="float-left font-regular home">
                <a href="/<%=params[:lang]%>"><%= get_lang_string("home")%></a>
              </li>
              <li class="float-left font-regular">
                <%= raw(get_brd_name(@theme))%>
              </li>
              <li class="float-left font-regular">
                <%=@title%>
              </li>                
            </ul>
          <%if @all_items.count > 0%>   
              <div class="slick-parent-container-inner">
                <div class="float-left w-100 slick-area">
                  <div class="slicks-container">
                    <div class="float-left w-100 slicks">
                      <div class="float-left w-100 ">
                        <div class="float-left w-100 slick-container slick-gap">
                          <div class="float-left w-100 slick-wrapper">
                            <div class="float-left w-100 app-slick-carousel">
                              <div class="float-left w-100 app-d-flex justify-content-between app-slick-container">
                                <h1 class="section-title3 font-black app-color1"><%=@title%></h1>
                              </div>
                              <div class="float-left w-100 app-slick-slider-container">
                                <div id="all_items">
                                <%if @layout_type == "t_2_3_movie" || @layout_type == "movies" 
                                 class_name = "vertical"
                                else
                                  class_name ="horizontal"
                                end%>
                                 <%@all_items.each do |i|%>
                                    <div class="listing-thumb <%= class_name%>-listing-thumb margin-bottom-10">
                                      <div style="width: 100%; display: inline-block;">
                                        <div class="slick-vertical-thumb">
                                          <article class="slick-vertical-thumb" style="">                                        
                                            <a href="<%=get_lang_url(i['seo_web_url'])%>" >
                                              <div class="thumbnail-container">
                                                <div class="card-img-container">
                                                  <%if @layout_type == "t_1_1_album" || @layout_type == "songs"%>
                                                    <img src="<%=i["thumbnails"]["small_2_3"]["url"]%>" class="img-loader lazy-img-loader loaded" loading="lazy" alt="<%=i["title"]%>" title="<%=i["title"]%>">
                                                  <%else%>
                                                    <img src="<%=get_image_url(i,@layout_type)%>" class="img-loader lazy-img-loader loaded" loading="lazy" alt="<%=i["title"]%>" title="<%=i["title"]%>">
                                                  <%end%>
                                                </div>  
                                              </div>                                            
                                              <div class="slick-thumb-details">
                                                <div class="content-title ellipsize"><%= i['ml_display_title'] rescue i['display_title']%></div>
                                                <!-- <div class="sub-info ellipsize"><%#=i['ml_genres'][0].capitalize rescue i['genres'][0].capitalize %> | <%#=i['ml_language'][0].capitalize rescue i['language']%> | <%#= i['ml_release_date'].split("-")[0] rescue i['release_date_string'].split("-")[0]%>
                                                </div>  -->
                                             </div>                                         
                                            </a>
                                            <div class="h-center">
                                              <%if i["content_definition"] == "TVOD"%>
                                                  <span class="buy-txt"><%= get_lang_string("buy") %></span>
                                              <%elsif i["access_control"]["is_free"] == false  && i["access_control"]["premium_tag"] == true && i["content_definition"] != "TVOD" && $region == "IN"%>
                                                 <span class="premium-img"><img src="/assets/premium_icon.svg" class="w-100" alt="" title=""></span>
                                              <%end%>
                                            </div>
                                            <div class="app-d-flex justify-content-end">
                                              <% if i['access_control']['is_free'] == true && i['theme'] == "episode"%>
                                                  <span class="free-txt text-uppercase">free</span>
                                              <% end %>
                                            </div> 
                                          </article>                                        
                                        </div>
                                      </div>
                                    </div>
                                  <%end%>
                                </div> 
                                <%if @next_page == "true"%> 
                                   <div class="text-center margin-bottom-25 margin-top-20" id="load_more_items_link"> <a href="javascript:void(0);" class="inline-block radius-button text-uppercase load_all_items" id="load_more_all_items"><%= get_lang_string("load_more")%></a></div>
                                <%end%>
                              </div>
                            </div>  
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div> 
              <%=render "layouts/page_height_setting"%>    
            <%else%>
              <div class="light no-items-found" style="margin-top:87px;">
                <img src="/assets/no_content.svg" class="margin-bottom-10 welcome_page_image margin-top-25"  alt="" title=""  >
                <p class="font-mbold margin-top-25 margin-bottom-0"><strong><%= get_lang_string("sorry")%></strong></p>
                <p class="font-mregular margin-top-0 margin-bottom-5"><%= get_lang_string("no_content")%></p>
                <p class="pull-left w-100 margin-top-20 margin-bottom-15 text-center">
                  <a href="/" class="text-uppercase radius-button"><%= get_lang_string("go_back")%></a>
                </p>
              </div>
               <%=render "layouts/page_height_setting"%>    
            <%end%>
          </div>  
        </section>
      </div>  
    </div>
  </div>
</div>
<input type="hidden" value="1" id="page_number">
<input type="hidden" name="layout_type" value="<%=@layout_type%>" class="items_layout_type">

<%=render "layouts/page_height_setting"%>    

<script type="text/javascript">
$(document).ready(function(){
  $(".scrollmenuwrap").hide();
  $("#load_more_all_items").click(function(){
    var tab_name =$("#net_head_title").text()
    Netcore_Browse(tab_name,"","")
    var video_theme = $(".items_layout_type").val();
    $(this).text("<%= get_lang_string("load_more")%>...");
    var pageno = $("#page_number").val();
    $.ajax({
    url: window.location.pathname,
    type: "GET",
    data: {
    page_no: pageno,
    theme_type: video_theme,
    lang: getShemarooCookies().shm_sel_lang
    },
    success: function(response,status){
      $("#load_more_all_items").text("<%= get_lang_string("load_more")%>");
      $("#page_number").val(response.pageno);
      var items = response.items
      for(i=0 ; i <items.length; i++){
        var item_det = items[i].split("$");
        if(video_theme == "t_2_3_movie" || video_theme == "movies"){
          $("#all_items").append('<div class="listing-thumb vertical-listing-thumb" style=""><div style="width: 100%; display: inline-block;"><div class="slick-vertical-thumb"><article class="slick-vertical-thumb" style=""><a href="'+item_det[2]+'"><div class="thumbnail-container"><div class="card-img-container"><img src="'+item_det[1]+'" class="img-loader lazy-img-loader loaded" loading="lazy" alt="'+item_det[0]+'" title="'+item_det[0]+'"></div></div><div class="slick-thumb-details"><div class="content-title ellipsize">'+item_det[0]+'</div><div class="sub-info ellipsize">'+item_det[4]+' | '+item_det[5]+' | '+item_det[6]+' </div></div></a><div class="h-center"><span class="premium-img" style="display:'+(item_det[3] == "true" ? "none" : "")+'"><img src="/assets/premium_icon.svg" alt="" title="" class="w-100"></span></div><div class="app-d-flex justify-content-end"><span class="free-txt text-uppercase" style="display:'+(item_det[7] == "episode" && item_det[8] == "true" ? "" : "none")+'">free</span></div></article></div></div></div>')
        }
        else{

          $("#all_items").append('<div class="listing-thumb horizontal-listing-thumb" style=""><div style="width: 100%; display: inline-block;"><div class="slick-vertical-thumb"><article class="slick-vertical-thumb" style=""><a href="'+item_det[2]+'"><div class="thumbnail-container"><div class="card-img-container"><img src="'+item_det[1]+'" class="img-loader lazy-img-loader loaded" loading="lazy" alt="'+item_det[0]+'" title="'+item_det[0]+'"></div></div><div class="slick-thumb-details"><div class="content-title ellipsize">'+item_det[0]+'</div><div class="sub-info ellipsize">'+item_det[4]+' | '+item_det[5]+' | '+item_det[6]+' </div></div></a><div class="h-center"><span class="premium-img" style="display:'+(item_det[3] == "true" ? "none" : "")+'"><img src="/assets/premium_icon.svg" alt="" title="" class="w-100"></span></div><div class="app-d-flex justify-content-end"><span class="free-txt text-uppercase" style="display:'+(item_det[7] == "episode" && item_det[8] == "true" ? "" : "none")+'">free</span></div></article></div></div></div>')

        }
      } console.log(response.next_page);
      if(response.next_page == "false"){
        $("#load_more_items_link").hide();
      }
      $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });

      $('article').hover(
      function() {
        $(this).addClass("expand")
      },
      function() {
        $(this).removeClass("expand")
      }
    );

    }
  });

  })

  $('article').hover(
    function() {
      $(this).addClass("expand")
    },
    function() {
      $(this).removeClass("expand")
    }
  );


  $(window).scroll(function(){
    var scroll = $(window).scrollTop(),
    doc_height = $(document).height(),
    window_height = $(window).height();
    var scrollPercent = ((scroll / (doc_height - window_height)) * 100).toFixed(0);
    if (scrollPercent == 10 || scrollPercent == 25  || scrollPercent == 50  || scrollPercent == 75 || scrollPercent == 100) {
      netcore_apxor_scoll_event('<%= params[:catalog_name] %>',scrollPercent)
    };
    
  })

  function netcore_apxor_scoll_event(name,scrollPercent){
    var user_state = $.cookie('user_actv_sub_status') != undefined ? $.cookie('user_actv_sub_status').toLowerCase() : "anonymous"    
    Apxor.logEvent("Scroll_Vertical",{
    "screen_name": name,
    'user_state': user_state,
    "depth": scrollPercent
    }, "Scroll_Vertical");

    smartech('dispatch', 'Scroll_Vertical', {
      "screen_name": name,
      "depth": scrollPercent,
      'user_state': user_state
    })


    branch.logEvent(
    "Scroll_Vertical",
      {"screen_name": name,
      'user_state': user_state,
      "depth": scrollPercent
    },
    function(err) { console.log(err); }
    );
  }

})

</script>